# Generated by Django 5.1.4 on 2024-12-05 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(unique=True)),
                ('short_url', models.CharField(max_length=7, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_count', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2025, 12, 5, 19, 41, 25, 665374, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
