# Generated by Django 5.1.4 on 2024-12-05 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 5, 20, 15, 40, 948669, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
