# Generated by Django 5.1.4 on 2024-12-06 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_alter_url_expires_at_alter_url_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 6, 18, 14, 57, 550790, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='url',
            name='original_url',
            field=models.URLField(),
        ),
    ]
